# Site Settings
title: gem5
sourceurl: "https://gem5.googlesource.com/public/gem5-website/+/refs/heads/stable/README.md"
url: "https://kbtxwer.gitee.io/gem5-doc"
defaults:
  -
    scope:
      path: ""
    values:
      layout: "page"
      
# Build Settings
sass:
  sass_dir: _sass

include: ['_pages']

site:
  baseurl: "https://kbtxwer.gitee.io/gem5-doc"

kramdown:
  input: GFM
  toc_levels: "1,2"
  auto_id: true

collections:
  pages:
    output: true
