# Site Settings
title: gem5
sourceurl: "https://gem5.googlesource.com/public/gem5-website/+/refs/heads/stable/README.md"
url: "http://localhost:4000"
baseurl: ""

defaults:
  -
    scope:
      path: ""
    values:
      layout: "page"

# Build Settings
sass:
  sass_dir: _sass

include: ['_pages']

kramdown:
  input: GFM
  toc_levels: "1,2"
  auto_id: true

collections:
  documentation:
    output: true
